/**
 * Self-Contained HTML Exporter.
 * Creates a single .html file with base64-embedded images and inline fonts.
 * Works offline, identical to the live preview.
 */

const fs = require('fs');
const path = require('path');
const { resolveTheme } = require('./themeEngine');
const { imageToDataUrl } = require('../utils/imageUtils');

/**
 * Generate a self-contained HTML preview file.
 *
 * @param {Object} heroData - Full hero data from the form
 * @param {Object} rendererHtml - The innerHTML of the preview container
 * @param {string} outputPath - Where to save the HTML
 * @returns {string} Path to the generated file
 */
async function exportHtml(heroData, rendererHtml, outputPath) {
  const theme = resolveTheme({
    category: heroData.category,
    subcategory: heroData.subcategory,
    team: heroData.team,
    colorDb: heroData.colorDb
  });

  // Read uploaded images and convert to base64
  const images = {};
  if (heroData.images) {
    for (const [key, img] of Object.entries(heroData.images)) {
      if (img && img.serverPath) {
        try {
          images[key] = imageToDataUrl(img.serverPath);
        } catch (e) {
          // Skip if file not found
        }
      } else if (img && img.dataUrl) {
        images[key] = img.dataUrl;
      }
    }
  }

  // Replace image src URLs in the renderer HTML with base64 data
  let html = rendererHtml;
  for (const [key, dataUrl] of Object.entries(images)) {
    // Replace any src that contains the upload filename
    if (heroData.images[key] && heroData.images[key].filename) {
      const filename = heroData.images[key].filename;
      html = html.replace(
        new RegExp(`src="[^"]*${escapeRegex(filename)}[^"]*"`, 'g'),
        `src="${dataUrl}"`
      );
    }
  }

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(heroData.name)} — Heroes Live Forever</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400&family=EB+Garamond:ital,wght@0,400;0,500;1,400&family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Oswald:wght@400;700&family=Bebas+Neue&family=Archivo+Black&family=Source+Sans+3:wght@400;600&display=swap');

  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    background: #111;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    font-family: 'EB Garamond', 'Georgia', serif;
    color: #e8e0d4;
    padding: 40px 20px;
  }
  .wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 24px;
  }
  .page-title {
    font-family: 'Cormorant Garamond', serif;
    font-size: 12px;
    letter-spacing: 5px;
    text-transform: uppercase;
    color: #555;
    font-weight: 300;
  }
</style>
</head>
<body>
  <div class="wrapper">
    <div class="page-title">Heroes Live Forever &middot; ${escapeHtml(heroData.frameSize)}</div>
    ${html}
    <div style="width: 620px; padding: 16px; border: 1px solid #1e1e1e; border-radius: 4px; background: #0d0d0d;">
      <h3 style="font-size: 9px; letter-spacing: 3px; text-transform: uppercase; color: #555; margin-bottom: 10px; font-weight: 400; font-family: sans-serif;">Production Notes</h3>
      <p style="font-size: 11px; line-height: 1.7; color: #555;">
        <span style="display: inline-block; padding: 2px 6px; background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 3px; font-size: 9px; color: #666; font-family: sans-serif;">CATEGORY</span> ${escapeHtml(heroData.category)}
        ${heroData.team ? ' &middot; ' + escapeHtml(heroData.team) : ''}
      </p>
      <p style="font-size: 11px; line-height: 1.7; color: #555;">
        <span style="display: inline-block; padding: 2px 6px; background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 3px; font-size: 9px; color: #666; font-family: sans-serif;">SIZE</span> ${escapeHtml(heroData.frameSize)} &middot; ${escapeHtml(heroData.layout)}
      </p>
      <p style="font-size: 10px; color: #c8a050; margin-top: 10px; padding-top: 10px; border-top: 1px solid #222; font-style: italic;">
        Generated by Heroes Live Forever Design Tool &middot; ${new Date().toLocaleDateString()}
      </p>
    </div>
  </div>
</body>
</html>`;

  fs.writeFileSync(outputPath, fullHtml, 'utf8');
  return outputPath;
}

function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = { exportHtml };
